FROM python:3.13-slim

LABEL org.opencontainers.image.source="https://github.com/CodyCBakerPhD/pozu-transcode"
LABEL org.opencontainers.image.description="A Docker image of the latest development version of pozu-transcode (bundles ffmpeg)."

RUN apt-get update \
    && apt-get install --no-install-recommends --yes ffmpeg \
    && rm -rf /var/lib/apt/lists/*

ADD ./ pozu-transcode
RUN cd pozu-transcode && python -m pip install --no-cache-dir .

CMD ["bash"]
